# Generated by Django 3.1.14 on 2023-02-22 12:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MsLogin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('email', models.EmailField(max_length=500)),
                ('password1', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MsBlacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msite.mslogin')),
            ],
        ),
    ]
