# Generated by Django 3.1.14 on 2023-02-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mslogin',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mslogin',
            name='password1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mslogin',
            name='password2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
