# Generated by Django 4.0.6 on 2023-03-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0003_msadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MsAdmin',
        ),
    ]
