# Generated by Django 4.0.6 on 2023-03-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0004_delete_msadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='msworks',
            name='report',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
